#!/bin/bash

if [[ -z "$1" ]];
then
	echo "Please, specify the playlist code as argument" 1>&2
	exit 1
fi
url="https://www.youtube.com/playlist?list=$1"

if [[ -z $(type -p html2) ]];
then
	echo "Please, install xml2 to use this script" 1>&2
	exit 1
fi

command=""
if [[ -n $(type -p wget) ]];
then
	command="wget -o /dev/null -O /tmp/playlist.html '$url'"
fi
if [[ -z "$command" ]] && [[ -n $(type -p curl) ]];
then
	command="curl -s -o /tmp/playlist.html '$url'"
fi
if [[ -z "$command" ]];
then
	echo "Please, install wget or curl to use this script" 1>&2
	exit 1
fi

eval $command
html2 < /tmp/playlist.html > /tmp/playlist.html2 2>/dev/null
grep "/html/body/div/div/div/div/div/div/div/div/div/div/ul/li/div/table/tbody/tr/@data-video-id=" /tmp/playlist.html2 > /tmp/playlist.html3
sed 's/\(.*\)=/https:\/\/www.youtube.com\/watch?v=/g' < /tmp/playlist.html3 > playlist.txt
