#!/bin/bash

if [[ -z "$1" ]];
then
	echo "Please, specify the playlist code as argument" 1>&2
	exit 1
fi
URL="https://www.youtube.com/playlist?list=$1"

if [[ -z $(type -p html2) ]];
then
	echo "Please, install xml2 to use this script" 1>&2
	exit 1
fi

TMPFILE=`mktemp /tmp/${tempfoo}.XXXXXX` || {
	echo "Tempoprary file creation failuer" 1>&2
	exit 1
}

COMMAND=""
if [[ -n $(type -p wget) ]];
then
	COMMAND="wget -o /dev/null -O '${TMPFILE}.html' '$URL'"
fi
if [[ -z "$COMMAND" ]] && [[ -n $(type -p curl) ]];
then
	COMMAND="curl -s -o '${TMPFILE}.html' '$URL'"
fi
if [[ -z "$COMMAND" ]];
then
	echo "Please, install wget or curl to use this script" 1>&2
	exit 1
fi

eval $COMMAND
html2 < "${TMPFILE}.html" > "${TMPFILE}.html2" 2>/dev/null
grep "/html/body/div/div/div/div/div/div/div/div/div/div/ul/li/div/table/tbody/tr/@data-video-id=" "${TMPFILE}.html2" > "${TMPFILE}.html3"
sed 's/\(.*\)=/https:\/\/www.youtube.com\/watch?v=/g' < "${TMPFILE}.html3" > playlist.txt

rm -f "${TMPFILE}"
